# analytics/train_model.py
"""
================================================================================
TRACK A (SYNTHETIC DATA) — CANONICAL TRAINING ENTRY POINT
================================================================================
This script trains the baseline ReconMind model entirely on the synthetic data 
generated by Groq (stored in `dataset/dataset_runs.csv`). 

For AgentDojo real-world data (Track B), use `train_agentdojo.py` instead.
For the final merged production model (Track C), run `scripts/merge_datasets.py` 
first, then run this script pointing to the merged directory:
  --dataset-dir dataset/merged

Usage:
  .venv/bin/python analytics/train_model.py
Optional args:
  --epochs 60
  --batch-size 32
  --lr 3e-4
  --output-dir models/deep
"""
import argparse
import logging
import sys
from pathlib import Path

# Add repo root to path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[
        logging.StreamHandler(sys.stdout),
        logging.FileHandler("models/deep/training.log", mode="w"),
    ]
)

from analytics.deep_model import train, TrainConfig

def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument("--epochs",      type=int,   default=60)
    p.add_argument("--batch-size",  type=int,   default=32)
    p.add_argument("--lr",          type=float, default=3e-4)
    p.add_argument("--output-dir",  type=str,   default="models/deep")
    p.add_argument("--dataset-dir", type=str,   default="dataset")
    p.add_argument("--no-cache",    action="store_true",
                   help="Recompute embeddings even if cache exists")
    return p.parse_args()

if __name__ == "__main__":
    args = parse_args()
    
    cfg = TrainConfig(
        epochs=args.epochs,
        batch_size=args.batch_size,
        lr=args.lr,
        output_dir=Path(args.output_dir),
        dataset_dir=Path(args.dataset_dir),
    )
    
    if args.no_cache:
        cache = cfg.output_dir / "text_embeddings.npy"
        if cache.exists():
            cache.unlink()
            print("Embedding cache cleared.")
    
    print(f"\nTraining ReconMind deep model")
    print(f"  Dataset: {cfg.dataset_dir}")
    print(f"  Output:  {cfg.output_dir}")
    print(f"  Epochs:  {cfg.epochs}")
    print(f"  Device:  cuda (RTX 4060)\n")
    
    model, metrics = train(cfg)
    
    print("\n" + "="*50)
    print("TRAINING COMPLETE")
    print("="*50)
    print(f"Binary Detection F1:    {metrics['binary_f1']:.4f}")
    print(f"Binary ROC-AUC:         {metrics['binary_roc_auc']:.4f}")
    print(f"Outcome Classification: {metrics['outcome_macro_f1']:.4f}")
    print(f"Type Classification:    {metrics['type_macro_f1']:.4f}")
    print(f"\nModel saved to: {cfg.output_dir}/best_model.pt")