-- reconmind/db/schema.sql
-- Single authority on DB schema. Updated for Milestone 3.
-- Tables: runs, events
-- Deferred (added in later milestones): edges, snapshots, embeddings
--
-- Conventions:
--   * All PKs are TEXT UUIDs generated by the application layer (not AUTOINCREMENT),
--     so IDs are portable across DB resets and reproducible in tests.
--   * Timestamps are ISO-8601 strings stored as TEXT (SQLite has no native DATETIME).
--   * JSON blobs (defense_config) are stored as TEXT; parsed by the app layer.
--   * FOREIGN KEY enforcement requires "PRAGMA foreign_keys = ON" at connection time
--     (init_db.py sets this).

-- ─────────────────────────────────────────────────────────────────────────────
-- runs
-- One row per simulation run (a full multi-hop attack scenario execution).
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS runs (
    run_id                  TEXT    PRIMARY KEY,          -- UUID, set by application
    scenario_id             TEXT    NOT NULL,             -- human-readable scenario name
    topology_type           TEXT    NOT NULL,             -- e.g. "linear", "star", "mesh"
    defense_config          TEXT,                         -- JSON blob: which defenses active + params
    injection_type          TEXT,                         -- e.g. "direct", "indirect", "none"
    entry_agent_id          TEXT,                         -- agent_id where attack enters
    critical_asset_agent_id TEXT,                         -- agent_id of target asset
    total_hops              INTEGER,                      -- total edges in topology
    hops_to_compromise      INTEGER,                      -- hops taken until compromise (NULL if not compromised)
    final_outcome           TEXT,                         -- "compromised" | "blocked" | "detected" | "timeout"
    detecting_defense       TEXT,                         -- which defense triggered detection (NULL if none)
    run_started_at          TEXT    NOT NULL,             -- ISO-8601 UTC
    run_ended_at            TEXT,                         -- ISO-8601 UTC; NULL if still running
    run_status              TEXT    NOT NULL DEFAULT 'running'  -- "running" | "completed" | "failed"
);

-- ─────────────────────────────────────────────────────────────────────────────
-- events
-- One row per agent-step within a run (every LLM call / tool call is one event).
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS events (
    event_id                    TEXT    PRIMARY KEY,      -- UUID, set by application
    run_id                      TEXT    NOT NULL
                                    REFERENCES runs(run_id) ON DELETE CASCADE,
    hop_index                   INTEGER NOT NULL,         -- 0-based hop counter within the run
    agent_id                    TEXT    NOT NULL,         -- which agent produced this event
    agent_role                  TEXT    NOT NULL,         -- e.g. "orchestrator", "subagent", "tool_proxy"
    input_prompt_text           TEXT,                     -- full prompt sent to the LLM (may be large)
    output_text                 TEXT,                     -- raw LLM response text
    tool_called                 TEXT,                     -- tool name if a tool was invoked, else NULL
    tool_result_status          TEXT,                     -- "success" | "error" | "timeout" | NULL
    memory_ops_summary          TEXT,                     -- human-readable summary of memory reads/writes
    model_name                  TEXT    NOT NULL,         -- e.g. "gpt-4o-mini", "llama3"
    latency_ms                  REAL,                     -- wall-clock LLM call latency in milliseconds
    defense_active              INTEGER NOT NULL DEFAULT 0,  -- 1 if any defense was active this event
    defense_triggered           INTEGER NOT NULL DEFAULT 0,  -- 1 if defense fired/blocked this event
    injection_present_this_event INTEGER NOT NULL DEFAULT 0, -- 1 if injected payload was in prompt
    injection_outcome           TEXT,                     -- "propagated" | "blocked" | "ignored" | NULL
    -- M3 additions: LLM call metadata (NULL for stub/non-LLM events)
    temperature                 REAL,                     -- sampling temperature used for this event
    input_tokens                INTEGER,                  -- prompt token count (from LLM response)
    output_tokens               INTEGER,                  -- completion token count (from LLM response)
    timestamp                   TEXT    NOT NULL          -- ISO-8601 UTC of when this event was logged
);

-- ─────────────────────────────────────────────────────────────────────────────
-- Indexes (added here so init_db.py is idempotent — CREATE INDEX IF NOT EXISTS)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_events_run_id    ON events(run_id);
CREATE INDEX IF NOT EXISTS idx_events_agent_id  ON events(agent_id);
CREATE INDEX IF NOT EXISTS idx_runs_scenario_id ON runs(scenario_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- session_memory
-- Shared memory store for agents during a run.
-- Append-only: every update creates a new version instead of overwriting.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS session_memory (
    memory_id                   TEXT    PRIMARY KEY,      -- UUID
    session_id                  TEXT    NOT NULL,         -- Links to the session/run
    key                         TEXT    NOT NULL,         -- The key being stored (e.g. "customer_context")
    value                       TEXT    NOT NULL,         -- The JSON/text value
    version                     INTEGER NOT NULL,         -- Monotonically increasing per key per session
    written_by_agent            TEXT    NOT NULL,         -- Which agent wrote this version
    timestamp                   TEXT    NOT NULL          -- ISO-8601 UTC
);

CREATE INDEX IF NOT EXISTS idx_session_memory_session_key ON session_memory(session_id, key);
